dest_dim: 1000
b: 100
r: 32

# ─── NETWORK ────────────────────────────────────────────────────────────────────

hidden:

# ─── TRAINING ───────────────────────────────────────────────────────────────────

batch_size:
begin_epoch:
end_epoch:
optimizer:
lr:
lr_step:
lr_factor:
weight_decay:

# ─── EVALUATION ─────────────────────────────────────────────────────────────────



# ─── DEBUG ──────────────────────────────────────────────────────────────────────


