name: "Wiki10" # dataset name, and data directory name
prefix: "Wiki10" # training dataset prefix, such as Eurlex_trimcumsum0.1
num_labels: 30938 # number of original labels
ori_dim: 101938 # feature dimension before feature hashing
train_size: 12300 #  number of training samples, the rest are in validation set
record_dir: "record" # preprocess results directory